#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Twist
from math import pi
import numpy as np
import matplotlib.pyplot as plt

class Turtlebot():
	def __init__(self):
    	rospy.init_node("turtlebot_move")
    	rospy.loginfo("Press Ctrl + C to terminate")
    	self.vel_pub = rospy.Publisher("cmd_vel_mux/input/navi", Twist, queue_size=10)
    	self.rate = rospy.Rate(10)
    	self.run()


	def run(self):
    	 vel = Twist()

    	vel.linear.x = 0.5
    	vel.angular.z = 0
    	for i in range(78):
        	self.vel_pub.publish(vel)
        	self.rate.sleep()



def visualization():
    # load csv file and plot trajectory 
    _, ax = plt.subplots(1)
    ax.set_aspect('equal')

    trajectory = np.loadtxt("trajectory.csv", delimiter=',')
    plt.plot(trajectory[:, 0], trajectory[:, 1], linewidth=2)

    plt.xlim(-1, 5)
    plt.ylim(-1, 5)
    plt.show()






    	 

if __name__ == '__main__':
	try:
    	whatever = Turtlebot()
	visualization()
	except rospy.ROSInterruptException:
    	rospy.loginfo("Action terminated.")
